language: python
python: 2.7
env:
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=py33
  - TOXENV=py34
matrix:
  allow_failures:
    - env: TOXENV=pypy
install:
  - pip install -U tox codecov
script: tox
after_success: codecov
